/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router. Do not edit it manually.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export const routeTree = rootRouteImport.addChildren({ IndexRoute })